version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      # Note: These must match the values provided in .env.docker (used by Prisma)
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'url-shrt-docker'
    ports:
      - '5433:5432'
    restart: unless-stopped
  app:
    build: .
    depends_on:
      - db
    ports:
      - '3000:3000'
    command: ['./wait-for-it.sh', 'db:5432', '--', 'bash', 'run.sh']
volumes:
  db:
